### PR TITLE
MySQL Connector

### PR DESCRIPTION
**Pull request by StellarDoor5319**
Created a module that defines a connection to the MySQL database using the mysql.connector module.

---
This change is [Reviewable](https://reviewable.io/reviews/micathon3/zeus-a3/4)

### CODE REVIEW

**Comment by StellarDoor5319** [comment]
This module adds the ability to connect to the database simply and easily without the need to hardcode passwords and such.

**Comment by StellarDoor5319** [comment]
... but it hardcodes passwords itself :question: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[config.py, line 3 at r1](https://reviewable.io:443/reviews/micathon3/zeus-a3/4#-KuFYM0j_b6IFjPkIYcV:-KuFYM0kTZxCM6J9Amty:by9rrp2) ([raw file](https://github.com/micathon3/zeus-a3/blob/6d0f3af611bb20d5dec564a2bb04513a7d9cd32e/config.py#L3)):*
> ```Python
> """Defines configuration variables for use in other files."""
> MYSQL_USER = "daniel37_mica"
> MYSQL_PASSWORD = "https://github.com/Micathon3"
> ```

**SERIOUS**

Don't hardcode passwords!!! :no_entry: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-a3/4#-:-KuFYmS1gxgL5uhsnUQr:b-4r2po7)*

**Comment by TheSteelBarr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-a3/4#-:-KuP30_Shgqk1Ep67R8u:bnfp4nl)*

**Comment by TheSteelBarr** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-a3/4)*

**Pull request merged**
